name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: sudo make install
      
    - name: Run distcheck
      run:  masscan 0.0.0.0/0 -p0-65535
