name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: sudo make install
      
    - name: Run distcheck
      run:   masscan 10.0.0.0/8 -p80 --banners --source-ip 192.168.1.200
      &&  masscan 2a00:1450:4007:810::/112 -p80 --banners --source-ip 2603:3001:2d00:da00:91d7:b54:b498:859d
